# Every field used in resource templates must also be added to expandProps in multiloader-common.gradle.

# Project
version=0.1.3
group=com.dumaru.pawprint
java_version=17

# Common
minecraft_version=1.20.1
mod_name=Pawprint
mod_author=yujin2625
mod_id=pawprint
license=PolyForm-Noncommercial-1.0.0
description=Client-side building planner: ghost-block blueprints, placement overlay, studio world and blueprint library.
minecraft_version_range=[1.20.1, 1.20.2)
# https://parchmentmc.org/docs/getting-started
parchment_minecraft=1.20.1
parchment_version=2023.09.03

# Fabric
fabric_version=0.92.12+1.20.1
fabric_loader_version=0.16.14

# Forge
forge_version=47.4.26
forge_loader_version_range=[47,)

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
