[package]
name = "pawprint"
version = "0.1.2"
description = "Pawprint blueprint editor"
license = "PolyForm-Noncommercial-1.0.0"
repository = "https://github.com/yujin2625/Pawprint"
edition = "2024"
rust-version = "1.90"

[lib]
name = "pawprint_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2.7.1", features = [] }

[dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
tauri = { version = "2.12.1", features = [] }
tauri-plugin-dialog = "2"
tauri-plugin-opener = "2"
tauri-plugin-window-state = "2"
tauri-plugin-single-instance = "2"
zip = { version = "2", default-features = false, features = ["deflate"] }


[profile.release]
codegen-units = 1
lto = true
opt-level = "s"
panic = "abort"
strip = true
