"""Builds the web font "Silver Pawprint" from Poppy Works' Silver (CC BY 4.0).

Changes from the original:
  - Hangul glyphs move down 100 units (1px at 19px) so they center with Latin text on the same line.
Output: public/fonts/silver-<subset>.woff split by Unicode range, and src/ui/fonts.css with matching
@font-face rules, so browsers only download the scripts a page uses.

Usage: python tools/build_font.py path/to/Silver.ttf   (needs: pip install fonttools)
"""
import os
import sys

from fontTools.subset import Options, Subsetter
from fontTools.ttLib import TTFont

HERE = os.path.dirname(os.path.abspath(__file__))
WEB = os.path.dirname(HERE)
OUT_FONTS = os.path.join(WEB, 'public', 'fonts')
OUT_CSS = os.path.join(WEB, 'src', 'ui', 'fonts.css')

HANGUL = [(0xAC00, 0xD7A3), (0x1100, 0x11FF), (0x3130, 0x318F), (0xA960, 0xA97F), (0xD7B0, 0xD7FF)]
SUBSETS = [
    ('latin', [(0x0000, 0x024F), (0x0300, 0x036F), (0x2000, 0x206F), (0x20A0, 0x20CF), (0x2100, 0x218F),
               (0x2190, 0x21FF), (0x2200, 0x22FF), (0x2500, 0x25FF), (0xFFFD, 0xFFFD)]),
    ('hangul', HANGUL),
    ('cjk', [(0x3000, 0x303F), (0x3040, 0x30FF), (0x3400, 0x4DBF), (0x4E00, 0x9FFF), (0xFF00, 0xFFEF)]),
    # Everything else the font has (Greek, Cyrillic, Georgian, …) goes into 'other'.
]
SHIFT = -100


def in_ranges(cp, ranges):
    return any(a <= cp <= b for a, b in ranges)


def shift_hangul(font):
    cmap = font.getBestCmap()
    glyf = font['glyf']
    for name in {cmap[cp] for cp in cmap if in_ranges(cp, HANGUL)}:
        glyph = glyf[name]
        if glyph.isComposite():
            for component in glyph.components:
                component.y += SHIFT
        elif glyph.numberOfContours > 0:
            glyph.coordinates.translate((0, SHIFT))
        else:
            continue
        glyph.recalcBounds(glyf)


def rename(font):
    for record in font['name'].names:
        text = record.toUnicode()
        if record.nameID in (1, 4, 16):
            record.string = text.replace('Silver', 'Silver Pawprint')
        elif record.nameID == 6:
            record.string = text.replace('Silver', 'SilverPawprint')


def css_ranges(codepoints):
    runs, start, prev = [], None, None
    for cp in sorted(codepoints):
        if start is None:
            start = prev = cp
        elif cp == prev + 1:
            prev = cp
        else:
            runs.append((start, prev))
            start = prev = cp
    if start is not None:
        runs.append((start, prev))
    return ', '.join('U+%X' % a if a == b else 'U+%X-%X' % (a, b) for a, b in runs)


def main(source):
    base = TTFont(source)
    shift_hangul(base)
    rename(base)
    tmp = os.path.join(OUT_FONTS, '_full.ttf')
    os.makedirs(OUT_FONTS, exist_ok=True)
    base.save(tmp)

    all_cps = set(base.getBestCmap())
    taken = set()
    groups = []
    for name, ranges in SUBSETS:
        cps = {cp for cp in all_cps if in_ranges(cp, ranges)}
        taken |= cps
        groups.append((name, cps))
    groups.append(('other', all_cps - taken))

    rules = []
    for name, cps in groups:
        if not cps:
            continue
        font = TTFont(tmp)
        options = Options()
        options.flavor = 'woff'
        options.layout_features = ['*']
        options.name_IDs = ['*']
        options.notdef_outline = True
        subsetter = Subsetter(options)
        subsetter.populate(unicodes=cps)
        subsetter.subset(font)
        font.flavor = 'woff'
        file = 'silver-%s.woff' % name
        font.save(os.path.join(OUT_FONTS, file))
        size = os.path.getsize(os.path.join(OUT_FONTS, file))
        print('%-7s %6d glyphs %8d bytes' % (name, len(cps), size))
        rules.append(
            "@font-face {\n"
            "  font-family: 'Silver Pawprint';\n"
            "  src: url('/fonts/%s') format('woff');\n"
            "  font-display: swap;\n"
            "  /* Silver draws text above the baseline only; these center it in the line box (19px: 15 up, 6 down). */\n"
            "  ascent-override: 78.947%%;\n"
            "  descent-override: 31.579%%;\n"
            "  line-gap-override: 0%%;\n"
            "  unicode-range: %s;\n"
            "}\n" % (file, css_ranges(cps)))
    os.remove(tmp)
    with open(OUT_CSS, 'w', encoding='utf-8', newline='\n') as f:
        f.write('/* Generated by tools/build_font.py — do not edit. Silver by Poppy Works (CC BY 4.0), modified. */\n')
        f.write('\n'.join(rules))


if __name__ == '__main__':
    if len(sys.argv) != 2:
        sys.exit(__doc__)
    main(sys.argv[1])
